---
default_roles:
    - system
    - pipewire
    - bluetooth
    - neofetch
    - yay
    - kitty
    - rust
    - zsh
    - fonts
    - starship
    - tmux
    - thefuck
    - firefox
    - codium
    - nvm
    - git
    - lazygit
    - fzf
    - bottom
    - ripgrep
    - eza
    - tldr
    - zoxide
    - bat
    - nvim
    - lazyvim
    - gaming
    - vlc
    - mpv
    - tailscale
