---
- name: Include Ubuntu tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"
  tags: [vlc]

- name: Include Arch tasks
  ansible.builtin.include_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
  tags: [vlc]
