---
- name: Add an Apt signing key for vscodium
  become: true
  apt_key:
      url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
      state: present
- name: 'Add repo'
  become: true
  apt_repository:
      repo: 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main'
- name: 'Install codium'
  become: true
  apt:
      name: codium
