---
- name: Cargo apps
  hosts: all
  connection: local
  tasks:
      - name: eza exists
        shell: 'eza -v'
        register: eza_exists
        ignore_errors: yes

      - name: Install eza (long task)
        when: eza_exists is failed
        become: false
        community.general.cargo:
            name: eza

      - name: Install starship
        community.general.cargo:
            name: starship
            locked: true
