---
- name: Install system software 
  hosts: all
  connection: local
  become: true
  tasks:
      - name: Update and upgrade apt packages
        apt:
            upgrade: 'yes'
            update_cache: 'yes'
            cache_valid_time: 86400 #One day

      - name: install system software
        package:
            name:
                - python3-dev
                - python3-pip
                - python3-setuptools

