---
- name: Check if bluetooth is already installed
  ansible.builtin.command: dpkg -s bluez
  register: bluetooth_installed
  failed_when: false
  changed_when: false
  tags: [bluetooth]

- name: Install bluetooth packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - bluez
    - bluez-tools
    - bluetooth
  when: bluetooth_installed.rc != 0
  tags: [bluetooth]

- name: Enable and start bluetooth service
  become: true
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
    state: started
  when: bluetooth_installed.rc != 0
  tags: [bluetooth]
