---
- name: Update and upgrade apt packages
  become: true
  apt:
      upgrade: 'yes'
      update_cache: 'yes'
      cache_valid_time: 86400 #One day

- name: install system software
  become: true
  package:
      name:
          - python3-dev
          - python3-pip
          - python3-setuptools


- name: Create ~/Documents/workspace directory
  become: false
  file:
      path: ~/Documents/workspace
      state: directory