---
- name: zoxide exists
  shell: 'zoxide --version'
  register: zoxide_exists
  ignore_errors: yes

- name: Install zoxide (long task)
  when: zoxide_exists is failed
  become: false
  community.general.cargo:
      name: zoxide

- name: Check if zoxide alias is set
  lineinfile:
    state: absent
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: "zoxide init zsh"
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Define zoxide if undefined
  lineinfile:
    state: present
    path: "{{ ansible_user_dir }}/.zshrc"
    line: "eval \"$(zoxide init zsh)\""
  when: check.found == 0

