
---
- name: install software
  package:
      name:
          - zsh

- name: Ensure zsh is the default shell
  become: true
  user:
      name: '{{ ansible_user_id }}'
      shell: 'chsh -s /bin/zsh {{ ansible_user_id }}'


- name: ~/.zshrc exists
  stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc_exist

- name: Init ~/.zshrc
  become: false
  when: zshrc_exist is failed
  template:
    src: .zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
