---
- name: Check if thefuck is installed
  shell: command -v thefuck
  register: thefuck_exists
  ignore_errors: yes

- name: Install thefuck homebrew
  when: thefuck_exists is failed
  community.general.homebrew:
      name: thefuck
      state: present

- name: Check if thefuck alias is set
  lineinfile:
    state: absent
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: "thefuck"
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Define thefuck if undefined
  lineinfile:
    state: present
    path: "{{ ansible_user_dir }}/.zshrc"
    line: "eval $(thefuck --alias)"
  when: check.found == 0
