---
- name: install tmux 
  package:
      name:
          - tmux
- name: Generate tmux config files
  become: false
  template:
      src: .tmux.conf.j2
      dest: "{{ ansible_env.HOME }}/.tmux.conf"