---
- name: eza exists
  shell: 'eza -v'
  register: eza_exists
  ignore_errors: yes

- name: Install eza (long task)
  when: eza_exists is failed
  become: false
  community.general.cargo:
      name: eza

- name: Check if eza alias is set
  lineinfile:
    state: absent
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: "ls=eza"
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Define eza if undefined
  lineinfile:
    state: present
    path: "{{ ansible_user_dir }}/.zshrc"
    line: "alias ls=eza\nalias ll='eza -la'"
  when: check.found == 0

- name: Update "eza" Rust package its latest version
  when: eza_exists.stdout != ''
  community.general.cargo:
    name: eza 
    state: latest