---
- name: Check if pipewire is already installed
  ansible.builtin.command: dpkg -s pipewire
  register: pipewire_installed
  failed_when: false
  changed_when: false
  tags: [pipewire]

- name: Install pipewire packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - pipewire
    - pipewire-pulse
    - pipewire-alsa
    - wireplumber
    - libspa-0.2-bluetooth
  when: pipewire_installed.rc != 0
  tags: [pipewire]

- name: Enable wireplumber user service
  ansible.builtin.systemd:
    name: wireplumber
    scope: user
    enabled: true
    state: started
  when: pipewire_installed.rc != 0
  tags: [pipewire]

- name: Enable pipewire-pulse user service
  ansible.builtin.systemd:
    name: pipewire-pulse
    scope: user
    enabled: true
    state: started
  when: pipewire_installed.rc != 0
  tags: [pipewire]
