---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
  tags: [alacritty]

- name: Run Arch Linux Tasks
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
  tags: [alacritty]
