---
- name: Install Alacritty
  become: true
  package:
      name:
          - alacritty

- name: Create ~/.config/alacritty directory
  become: false
  file:
      path: ~/.config/alacritty
      state: directory

- name: Generate alacritty config files
  become: false
  copy:
      src: alacritty.yml
      dest: ~/.config/alacritty/alacritty.yml
